# Generated by Django 5.0.2 on 2024-11-29 11:23

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicerequest_id_servicerequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_id',
            field=models.BigIntegerField(default=services.models.ServiceRequest.generate_request_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('Technical Support', 'Technical Support'), ('Bill Payment Inquiry', 'Bill Payment Inquiry'), ('Scheduled Maintenance Inquiry', 'Scheduled Maintenance Inquiry'), ('Change of Address', 'Change of Address'), ('Feature Request', 'Feature Request'), ('Other', 'Other')], default='Technical Support', max_length=50),
        ),
    ]
